name: Scan codebase for secrets

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  secret-scan:
    uses: Onboardbase/securelog-scan/.github/workflows/securelog-scan.yml@main
    with:
      exclude: 'node_modules,dist'
      commits: 100
      # changed: true
