name: Scan codebase for secrets
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  secret-scan:
    uses: Onboardbase/securelog-scan@main
    with:
      exclude: 'node_modules,dist'
      commits: 100
      changed: true
